const contractAddress = "0xCF5e8762ea8451f02dF8C1C8021Aea270a25bC16";
const abi = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  {
    inputs: [],
    name: "authorIndexCurrent",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "authorIndexSort",
    outputs: [
      { internalType: "string", name: "id", type: "string" },
      { internalType: "bool", name: "exists", type: "bool" },
      { internalType: "uint256", name: "myIndex", type: "uint256" },
      { internalType: "address", name: "authorAddress", type: "address" },
      { internalType: "string", name: "authorName", type: "string" },
      { internalType: "string", name: "authorDescription", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "authors",
    outputs: [
      { internalType: "string", name: "id", type: "string" },
      { internalType: "bool", name: "exists", type: "bool" },
      { internalType: "uint256", name: "myIndex", type: "uint256" },
      { internalType: "address", name: "authorAddress", type: "address" },
      { internalType: "string", name: "authorName", type: "string" },
      { internalType: "string", name: "authorDescription", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "authorsIdSort",
    outputs: [
      { internalType: "string", name: "id", type: "string" },
      { internalType: "bool", name: "exists", type: "bool" },
      { internalType: "uint256", name: "myIndex", type: "uint256" },
      { internalType: "address", name: "authorAddress", type: "address" },
      { internalType: "string", name: "authorName", type: "string" },
      { internalType: "string", name: "authorDescription", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "authorId", type: "string" },
      { internalType: "string", name: "authorName", type: "string" },
      { internalType: "string", name: "authorDescription", type: "string" },
    ],
    name: "createAuthor",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "postId", type: "string" },
      { internalType: "string", name: "title", type: "string" },
      { internalType: "string", name: "content", type: "string" },
      { internalType: "string", name: "bannerUrl", type: "string" },
    ],
    name: "createPost",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_to", type: "address" }],
    name: "donate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_name", type: "string" },
      { internalType: "string", name: "_description", type: "string" },
    ],
    name: "editProfile",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "followingIds", type: "string" }],
    name: "follow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "authorAddr", type: "address" }],
    name: "getFollowingByAddr",
    outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "id", type: "string" }],
    name: "getFollowingByID",
    outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "authorAddress", type: "address" },
    ],
    name: "getPostsByAuthorAddress",
    outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "id", type: "string" }],
    name: "getPostsByAuthorID",
    outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "indexAuthorCurr", type: "uint256" },
    ],
    name: "getPostsByAuthorIndex",
    outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "postIndexCurrent",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "postIndexSort",
    outputs: [
      { internalType: "string", name: "id", type: "string" },
      { internalType: "bool", name: "exists", type: "bool" },
      { internalType: "address", name: "author", type: "address" },
      { internalType: "string", name: "authorId", type: "string" },
      { internalType: "string", name: "authorName", type: "string" },
      { internalType: "string", name: "authorDescription", type: "string" },
      { internalType: "address", name: "authorAddr", type: "address" },
      { internalType: "string", name: "title", type: "string" },
      { internalType: "string", name: "content", type: "string" },
      { internalType: "string", name: "bannerUrl", type: "string" },
      { internalType: "uint256", name: "timestamp", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "posts",
    outputs: [
      { internalType: "string", name: "id", type: "string" },
      { internalType: "bool", name: "exists", type: "bool" },
      { internalType: "address", name: "author", type: "address" },
      { internalType: "string", name: "authorId", type: "string" },
      { internalType: "string", name: "authorName", type: "string" },
      { internalType: "string", name: "authorDescription", type: "string" },
      { internalType: "address", name: "authorAddr", type: "address" },
      { internalType: "string", name: "title", type: "string" },
      { internalType: "string", name: "content", type: "string" },
      { internalType: "string", name: "bannerUrl", type: "string" },
      { internalType: "uint256", name: "timestamp", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "_walletToDonate",
        type: "address",
      },
    ],
    name: "splitEther",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "tokenAddress", type: "address" },
    ],
    name: "withdrawAToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawETH",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
export { contractAddress, abi };
